<a href="https://colab.research.google.com/github/e-junior/Data-Science/blob/main/indice_ibov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df_ibov = pd.read_csv('ibov_index.csv')

In [4]:
df_ibov.head()

         Data   Último  Abertura   Máxima   Mínima   Vol.    Var%
0  28.08.2025  141.640   139.206  142.138  139.206  5,84M   1,75%
1  27.08.2025  139.206   137.773  139.281  137.456  6,61B   1,04%
2  26.08.2025  137.771   138.026  138.037  137.058  8,45B  -0,18%
3  25.08.2025  138.025   137.971  138.890  137.971  5,99B   0,04%
4  22.08.2025  137.968   134.511  138.072  134.511  9,32B   2,57%

In [5]:
df_ibov.tail()

           Data   Último  Abertura   Máxima   Mínima    Vol.    Var%
659  06.01.2023  108.964   107.642  109.433  107.642  12,63M   1,23%
660  05.01.2023  107.641   105.336  107.743  105.333  15,51M   2,19%
661  04.01.2023  105.334   104.167  105.627  103.915  14,45M   1,12%
662  03.01.2023  104.166   106.377  106.684  103.852  14,47M  -2,08%
663  02.01.2023  106.376   109.734  109.734  105.981   8,13M  -3,06%

In [6]:
df_ibov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Data      664 non-null    object
 1   Último    664 non-null    float64
 2   Abertura  664 non-null    float64
 3   Máxima    664 non-null    float64
 4   Mínima    664 non-null    float64
 5   Vol.      664 non-null    object
 6   Var%      664 non-null    object
dtypes: float64(4), object(3)
memory usage: 36.4+ KB

In [10]:
# renomeando colunas

df_ibov.rename(columns={'Data':'data', 'Último': 'ultimo', 'Abertura' : 'abertura', 'Máxima': 'maxima', 'Mínima' : 'minima', 'Vol.': 'vol', 'Var%': 'variacao'}, inplace=True)

In [20]:
# convertendo coluna data em objeto para datetime

df_ibov['data'] = pd.to_datetime(df_ibov['data'], dayfirst=True, errors='coerce')

#ainda nao sei se consigo fazer operações de data com esse formato

In [25]:
#convertendo valores de coluna vol para float

def convert_volume(vol_str):
    vol_str = vol_str.replace(',', '.')
    if 'M' in vol_str:
        return float(vol_str.replace('M', '')) * 1_000_000
    elif 'B' in vol_str:
        return float(vol_str.replace('B', '')) * 1_000_000_000
    else:
        return float(vol_str)

df_ibov['vol'] = df_ibov['vol'].apply(convert_volume)

In [30]:
#convertendo valores de coluna variacao para float centesimal

def convert_variacao(variacao_str):
    variacao_str = variacao_str.replace(',', '.')
    if '%' in variacao_str:
        return float(variacao_str.replace('%', '')) / 100
    else:
        return float(variacao_str) / 100

df_ibov['variacao'] = df_ibov['variacao'].apply(convert_variacao)

In [31]:
df_ibov.head()

        data   ultimo  abertura   maxima   minima           vol  variacao
0 2025-08-28  141.640   139.206  142.138  139.206  5.840000e+06    0.0175
1 2025-08-27  139.206   137.773  139.281  137.456  6.610000e+09    0.0104
2 2025-08-26  137.771   138.026  138.037  137.058  8.450000e+09   -0.0018
3 2025-08-25  138.025   137.971  138.890  137.971  5.990000e+09    0.0004
4 2025-08-22  137.968   134.511  138.072  134.511  9.320000e+09    0.0257